# Brain Tumor Detection

### For Google Colab Users

In [ ]:
#@title ## Mount Your Google Drive & Map your Directory
#@markdown Please run this cell (`Ctrl+Enter` or `Shift+Enter`) and follow the steps printed bellow.
import os

from google.colab import drive
drive.mount('/content/gdrive')

# check Google Drive is mounted
if not os.path.isdir("/content/gdrive"):
  raise FileNotFoundError("Your Google Drive isn't mounted. Please run the above cell.")

assignment_dir = "/content/gdrive/MyDrive/workspace/BrainTumorDetection"  #@param{type:"string"}
assignment_dest = "/content/project"

# create symbolic link
!rm -f {assignment_dest}
!ln -s "{assignment_dir}" "{assignment_dest}"
print(f'Succesfully mapped (ln -s) "{assignment_dest}" -> "{assignment_dir}"')

# cd to linked dir
%cd -q {assignment_dest}
print(f'Succesfully changed directory (cd) to "{assignment_dest}"')

Mounted at /content/gdrive
Succesfully mapped (ln -s) "/content/project" -> "/content/gdrive/MyDrive/workspace/BrainTumorDetection"
Succesfully changed directory (cd) to "/content/project"


### Init

In [1]:
#@title ##Init

#@markdown Import required modules and observe your resources

# auto reload
%load_ext autoreload
%autoreload 2

# import
import torch
import torchvision
from PIL import Image
import matplotlib.pyplot as plt
import random
import os
import wandb
wandb.login()

from experiment import Experiment
from network import get_model

# Show resources
!nvidia-smi

wandb: Currently logged in as: antebi-itai (use `wandb login --relogin` to force relogin)


Sat Jun 26 21:47:13 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
| N/A   36C    P0    45W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Experiment

In [2]:
# params
config = {
"model_name": "vgg19",
"data_train_path": os.path.join(".", "Data", "Training"),
"data_test_path": os.path.join(".", "Data", "Testing"),
"epochs": 3,
"train_batch_size": 200,
"lr": 1e-4,
"heatmap_batch_size": 1,
"occlusion_size": (60,60),
"heat_layers" : [2],
"shuffle_data": True,
"device": "cuda"
}

experiment = Experiment(config)
# train
with wandb.init(project="BrainTumorDetection", config=config):
    #experiment.train_model()
    heat_map = experiment.generate_heatmap(r"./Data/Testing/glioma_tumor/image.jpg")

|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  545997 KB |  545997 KB |  545997 KB |       0 B  |
|       from large pool |  544128 KB |  544128 KB |  544128 KB |       0 B  |
|       from small pool |    1869 KB |    1869 KB |    1869 KB |       0 B  |
|---------------------------------------------------------------------------|
| Active memory         |  545997 KB |  545997 KB |  545997 KB |       0 B  |
|       from large pool |  544128 KB |  544128 KB |  544128 KB |

ipdb>  n


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(70)generate_heatmap()
     68         import pdb; pdb.set_trace()
     69         heatmap = []
---> 70         for idx, images in occluded_loader:
     71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images



ipdb>  


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(71)generate_heatmap()
     69         heatmap = []
     70         for idx, images in occluded_loader:
---> 71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images
     73           self.model(occluded_images)



ipdb>  idx


tensor([0])


ipdb>  images


tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]])


ipdb>  images.shape


torch.Size([1, 3, 256, 256])


ipdb>  n


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(73)generate_heatmap()
     71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images
---> 73           self.model(occluded_images)
     74 
     75         features = fe.flush_activations()



ipdb>  images


tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]])


ipdb>  images.device


device(type='cpu')


ipdb>  sefl.device


*** NameError: name 'sefl' is not defined


ipdb>  occluded_images.device


device(type='cuda', index=0)


ipdb>  n


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(70)generate_heatmap()
     68         import pdb; pdb.set_trace()
     69         heatmap = []
---> 70         for idx, images in occluded_loader:
     71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images



ipdb>  print(torch.cuda.memory_summary))


*** SyntaxError: unmatched ')'


ipdb>  print(torch.cuda.memory_summary())


|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  595918 KB |  705998 KB |    1170 MB |  602564 KB |
|       from large pool |  593280 KB |  698752 KB |    1154 MB |  589067 KB |
|       from small pool |    2638 KB |    7800 KB |      15 MB |   13497 KB |
|---------------------------------------------------------------------------|
| Active memory         |  595918 KB |  705998 KB |    1170 MB |  602564 KB |
|       from large pool |  593280 KB |  698752 KB |    1154 MB |

ipdb>  n


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(71)generate_heatmap()
     69         heatmap = []
     70         for idx, images in occluded_loader:
---> 71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images
     73           self.model(occluded_images)



ipdb>  n


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(73)generate_heatmap()
     71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images
---> 73           self.model(occluded_images)
     74 
     75         features = fe.flush_activations()



ipdb>  


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(70)generate_heatmap()
     68         import pdb; pdb.set_trace()
     69         heatmap = []
---> 70         for idx, images in occluded_loader:
     71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images



ipdb>  print(torch.cuda.memory_summary())


|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  613070 KB |  723150 KB |    1489 MB |     890 MB |
|       from large pool |  609664 KB |  715136 KB |    1466 MB |     870 MB |
|       from small pool |    3406 KB |    8569 KB |      23 MB |      19 MB |
|---------------------------------------------------------------------------|
| Active memory         |  613070 KB |  723150 KB |    1489 MB |     890 MB |
|       from large pool |  609664 KB |  715136 KB |    1466 MB |

ipdb>  n


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(71)generate_heatmap()
     69         heatmap = []
     70         for idx, images in occluded_loader:
---> 71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images
     73           self.model(occluded_images)



ipdb>  


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(73)generate_heatmap()
     71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images
---> 73           self.model(occluded_images)
     74 
     75         features = fe.flush_activations()



ipdb>  


> /home/labs/waic/itaian/BrainTumorDetection/experiment.py(70)generate_heatmap()
     68         import pdb; pdb.set_trace()
     69         heatmap = []
---> 70         for idx, images in occluded_loader:
     71           occluded_images = images.to(device=self.device)
     72           # Run the model on batched occluded images



ipdb>  print(torch.cuda.memory_summary())


|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  630223 KB |  740303 KB |    1807 MB |    1192 MB |
|       from large pool |  626048 KB |  731520 KB |    1777 MB |    1166 MB |
|       from small pool |    4175 KB |    9337 KB |      30 MB |      26 MB |
|---------------------------------------------------------------------------|
| Active memory         |  630223 KB |  740303 KB |    1807 MB |    1192 MB |
|       from large pool |  626048 KB |  731520 KB |    1777 MB |

ipdb>  self.model


VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padd

ipdb>  self.model.features[2]


Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


ipdb>  exit


BdbQuit: 